services:
   swagger:
      image: indhu286/swaggerapp:latest
      container_name: swagger_app
      build:
         context: ./nodejs-auto-swagger-doc-generator
      ports:
         - "8081:3000"
      env_file:
         - .env
      depends_on:
         - mongo

   mongo:
      image: mongo:6.0
      container_name: swagger_db
      restart: always
      environment:
         MONGO_INITDB_ROOT_USERNAME: indhu
         MONGO_INITDB_ROOT_PASSWORD: hello123
