services:
   swagger:
      image: indhu286/swaggerapp:latest
    
      
      ports:
         - "8081:3000"
      environment:
         - MONGO_URI:${MONGO_URI}
         - JWT_SECRET:${JWT_SECRET}         
      depends_on:
         - mongo

   mongo:
      image: mongo:6.0
      
      restart: always
      volumes: 
         - mongo_data:/data/db
volumes:
      mongo_data:
         
