services:
   swagger:
      image: indhu286/swaggerapp:latest
    
      
      ports:
         - "8081:3000"
      environment:
         - MONGO_URI=mongodb://mongo:27017/swaggerdb
         - JWT_SECRET=${JWT_SECRET}         
      depends_on:
         - mongo

   mongo:
      image: mongo:6.0
      environment:
         - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
         - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      restart: always
      volumes: 
         - mongo_data:/data/db
volumes:
      mongo_data:
         
