services:
   swagger:
      image: node:18
      container_name: swagger_app
      build:
         context: ./nodejs-auto-swagger-doc-generator
      ports:
         -"8080:3000"
      env_file:
         - .env
      depends_on:
         -mongo

   mongo:
      image: mongo
      container_name: swagger_db
      restart: always
      environment:
         MONGO_INITDB_USERNAME: indhu
         MONGO_INITDB_PASSWORD: hello123
